### ISSUE TITLE
Failed to start node on update latest (node - 1.8.4,  middleware_version – 0.1.17)

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanche-rosetta#146]
Hello Team, @rajranjan0608 

**On update from 1.7.6 to 1.8.4, node unable to start with previous data & logs directory, while it’s working with new data & logs directory, it’s start syncing from scratch.**

Here is the steps

**Clone avalanche-rosetta  --> sudo git clone https://github.com/ava-labs/avalanche-rosetta.git**

**Create docker image --> sudo docker build --no-cache --build-arg AVALANCHE_VERSION=${AVALANCHE_VERSION} --build-arg ROSETTA_VERSION=${GIT_COMMIT} -t avaplatform/avalanche-rosetta:v1.8.4 .**

**Run docker image --> sudo docker run -d --name avalanche-mainnet-3332 --rm -v $PWD/data:/data -v $PWD/logs:/root/.avalanchego -e AVALANCHE_NETWORK=Mainnet -e AVALANCHE_CHAIN=43114 -e AVALANCHE_MODE=online -p 3332:8080 -p 9650:9650 -p 9651:9651 avaplatform/avalanche-rosetta:v1.8.4**

**Complete Logs**

2022/09/08 06:10:38 starting command: /app/rosetta-server [-config rosetta-config.json],
2022/09/08 06:10:38 starting command: /app/avalanchego [--config-file /app/avalanchego-config.json],
2022/09/08 06:10:39 starting server in online mode,
2022/09/08 06:10:39 using avax (chain="Avalanche" chainid="43114" network="Mainnet") rpc endpoint: http://localhost:9650,
2022/09/08 06:10:39 starting rosetta server at 0.0.0.0:8080,
[09-08|06:10:46.642] WARN process/process.go:97 UPnP or NAT-PMP router attach failed, you may not be listening publicly. Please confirm the settings in your router,
[09-08|06:10:46.642] INFO node/node.go:1221 initializing node {"version": "avalanche/1.8.4", "nodeID": "NodeID-6Y59nLZkUieX6RaNPBg2zwG8MjmnKQt7F", "config": {"httpConfig":{"apiConfig":{"authConfig":{"apiRequireAuthToken":false},"indexerConfig":{"indexAPIEnabled":false,"indexAllowIncomplete":false},"ipcConfig":{"ipcAPIEnabled":false,"ipcPath":"/tmp","ipcDefaultChainIDs":null},"adminAPIEnabled":false,"infoAPIEnabled":true,"keystoreAPIEnabled":false,"metricsAPIEnabled":true,"healthAPIEnabled":true},"httpHost":"0.0.0.0","httpPort":9650,"httpsEnabled":false,"apiAllowedOrigins":["*"],"shutdownTimeout":10000000000,"shutdownWait":0},"ipConfig":{"ip":{"ip":"192.168.80.2","port":9651},"ipResolutionFrequency":300000000000,"attemptedNATTraversal":true},"stakingConfig":{"uptimeRequirement":0.8,"minValidatorStake":2000000000000,"maxValidatorStake":3000000000000000,"minDelegatorStake":25000000000,"minDelegationFee":20000,"minStakeDuration":1209600000000000,"maxStakeDuration":31536000000000000,"rewardConfig":{"maxConsumptionRate":120000,"minConsumptionRate":100000,"mintingPeriod":31536000000000000,"supplyCap":720000000000000000},"enableStaking":true,"disabledStakingWeight":100,"stakingKeyPath":"/root/.avalanchego/staking/staker.key","stakingCertPath":"/root/.avalanchego/staking/staker.crt"},"txFeeConfig":{"txFee":1000000,"createAssetTxFee":10000000,"createSubnetTxFee":1000000000,"transformSubnetTxFee":1000000000,"createBlockchainTxFee":1000000000,"addPrimaryNetworkValidatorFee":0,"addPrimaryNetworkDelegatorFee":0,"addSubnetValidatorFee":1000000,"addSubnetDelegatorFee":1000000},"stateSyncConfig":{"stateSyncIDs":null,"stateSyncIPs":null},"bootstrapConfig":{"retryBootstrap":true,"retryBootstrapWarnFrequency":50,"bootstrapBeaconConnectionTimeout":60000000000,"bootstrapAncestorsMaxContainersSent":2000,"bootstrapAncestorsMaxContainersReceived":2000,"bootstrapMaxTimeGetAncestors":50000000,"bootstrapIDs":["NodeID-9T7NXBFpp8LWCyc58YdKNoowDipdVKAWz","NodeID-Hr78Fy8uDYiRYocRYHXp4eLCYeb8x5UuM","NodeID-A6onFGyJjA37EZ7kYHANMR1PFRT8NmXrF","NodeID-4kCLS16Wy73nt1Zm54jFZsL7Msrv3UCeJ","NodeID-QKGoUvqcgormCoMj6yPw9isY7DX9H4mdd"],"bootstrapIPs":[{"ip":"18.202.190.40","port":9651},{"ip":"54.93.182.129","port":9651},{"ip":"54.94.43.49","port":9651},{"ip":"122.248.199.127","port":9651},{"ip":"18.162.161.230","port":9651}]},"databaseConfig":{"path":"/data/mainnet","name":"leveldb"},"avaxAssetID":"FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z","networkID":1,"enableAssertions":true,"healthCheckFreq":30000000000,"networkConfig":{"healthConfig":{"minConnectedPeers":1,"maxTimeSinceMsgReceived":60000000000,"maxTimeSinceMsgSent":60000000000,"maxPortionSendQueueBytesFull":0.9,"maxSendFailRate":0.9,"sendFailRateHalflife":10000000000},"peerListGossipConfig":{"peerListNumValidatorIPs":15,"peerListValidatorGossipSize":20,"peerListNonValidatorGossipSize":10,"peerListPeersGossipSize":0,"peerListGossipFreq":60000000000},"timeoutConfigs":{"pingPongTimeout":30000000000,"readHandshakeTimeout":15000000000},"delayConfig":{"initialReconnectDelay":1000000000,"maxReconnectDelay":3600000000000},"throttlerConfig":{"inboundConnUpgradeThrottlerConfig":{"upgradeCooldown":10000000000,"maxRecentConnsUpgraded":2560},"inboundMsgThrottlerConfig":{"byteThrottlerConfig":{"vdrAllocSize":33554432,"atLargeAllocSize":6291456,"nodeMaxAtLargeBytes":2097152},"bandwidthThrottlerConfig":{"bandwidthRefillRate":524288,"bandwidthMaxBurstRate":2097152},"cpuThrottlerConfig":{"maxRecheckDelay":5000000000},"diskThrottlerConfig":{"maxRecheckDelay":5000000000},"maxProcessingMsgsPerNode":1024},"outboundMsgThrottlerConfig":{"vdrAllocSize":33554432,"atLargeAllocSize":33554432,"nodeMaxAtLargeBytes":2097152},"maxInboundConnsPerSec":256},"dialerConfig":{"throttleRps":50,"connectionTimeout":30000000000},"tlsKeyLogFile":"","namespace":"","myNodeID":"NodeID-111111111111111111116DBWJs","myIP":null,"networkID":0,"maxClockDifference":60000000000,"pingFrequency":22500000000,"allowPrivateIPs":true,"compressionEnabled":true,"whitelistedSubnets":[],"beacons":null,"validators":null,"uptimeMetricFreq":30000000000,"uptimeRequirement":0,"requireValidatorToConnect":true,"maximumInboundMessageTimeout":10000000000,"peerReadBufferSize":8192,"peerWriteBufferSize":8192},"gossipConfig":{"gossipAcceptedFrontierValidatorSize":0,"gossipAcceptedFrontierNonValidatorSize":0,"gossipAcceptedFrontierPeerSize":15,"gossipOnAcceptValidatorSize":0,"gossipOnAcceptNonValidatorSize":0,"gossipOnAcceptPeerSize":10,"appGossipValidatorSize":10,"appGossipNonValidatorSize":0,"appGossipPeerSize":0},"adaptiveTimeoutConfig":{"initialTimeout":5000000000,"minimumTimeout":2000000000,"maximumTimeout":10000000000,"timeoutCoefficient":2,"timeoutHalflife":300000000000},"benchlistConfig":{"threshold":10,"minimumFailingDuration":150000000000,"duration":900000000000,"maxPortion":0.08333333333333333},"profilerConfig":{"dir":"/root/.avalanchego/profiles","enabled":false,"freq":900000000000,"maxNumFiles":5},"loggingConfig":{"maxSize":8,"maxFiles":7,"maxAge":0,"directory":"/root/.avalanchego/logs","compress":false,"disableWriterDisplaying":false,"assertions":false,"logLevel":"INFO","displayLevel":"INFO","logFormat":"PLAIN"},"pluginDir":"/app/plugins","fdLimit":32768,"consensusParams":{"k":20,"alpha":15,"betaVirtuous":15,"betaRogue":20,"concurrentRepolls":4,"optimalProcessing":50,"maxOutstandingItems":1024,"maxItemProcessingTime":120000000000,"mixedQueryNumPushVdr":10,"mixedQueryNumPushNonVdr":0,"parents":5,"batchSize":30},"meterVMEnabled":true,"routerHealthConfig":{"maxDropRate":1,"maxDropRateHalflife":10000000000,"maxOutstandingRequests":1024,"maxOutstandingDuration":300000000000,"maxRunTimeRequests":10000000000},"consensusShutdownTimeout":30000000000,"consensusGossipFreq":10000000000,"whitelistedSubnets":[],"subnetConfigs":{},"systemTrackerProcessingHalflife":15000000000,"systemTrackerFrequency":500000000,"systemTrackerCPUHalflife":15000000000,"systemTrackerDiskHalflife":60000000000,"cpuTargeterConfig":{"vdrAlloc":16,"maxNonVdrUsage":12.8,"maxNonVdrNodeUsage":2},"diskTargeterConfig":{"vdrAlloc":1073741824000,"maxNonVdrUsage":1073741824000,"maxNonVdrNodeUsage":1073741824000},"requiredAvailableDiskSpace":536870912,"warningThresholdAvailableDiskSpace":1073741824}},
[09-08|06:10:46.643] INFO node/node.go:583 initializing API server,
[09-08|06:10:46.643] INFO server/server.go:138 API created {"allowedOrigins": ["*"]},
[09-08|06:10:46.643] INFO node/node.go:890 initializing metrics API,
[09-08|06:10:46.643] INFO server/server.go:298 adding route {"url": "/ext/metrics", "endpoint": ""},
[09-08|06:10:46.643] INFO leveldb/db.go:202 creating new leveldb {"config": {"blockCacheCapacity":12582912,"blockSize":0,"compactionExpandLimitFactor":0,"compactionGPOverlapsFactor":0,"compactionL0Trigger":0,"compactionSourceLimitFactor":0,"compactionTableSize":0,"compactionTableSizeMultiplier":0,"compactionTableSizeMultiplierPerLevel":null,"compactionTotalSize":0,"compactionTotalSizeMultiplier":0,"disableSeeksCompaction":true,"openFilesCacheCapacity":1024,"writeBuffer":6291456,"filterBitsPerKey":10,"maxManifestFileSize":9223372036854775807,"metricUpdateFrequency":10000000000}},
[09-08|06:10:57.386] INFO node/node.go:475 initializing database {"dbVersion": "v1.4.5"},
[09-08|06:10:57.397] INFO node/node.go:844 initializing keystore,
[09-08|06:10:57.397] INFO node/node.go:852 skipping keystore API initialization because it has been disabled,
[09-08|06:10:57.397] INFO node/node.go:836 initializing SharedMemory,
[09-08|06:10:57.418] INFO node/node.go:218 initializing networking {"currentNodeIP": "192.168.80.2:9651"},
[09-08|06:10:57.419] INFO node/node.go:1009 initializing Health API,
[09-08|06:10:57.419] INFO server/server.go:298 adding route {"url": "/ext/health", "endpoint": ""},
[09-08|06:10:57.419] INFO server/server.go:298 adding route {"url": "/ext/health", "endpoint": "/readiness"},
[09-08|06:10:57.419] INFO server/server.go:298 adding route {"url": "/ext/health", "endpoint": "/health"},
[09-08|06:10:57.419] INFO server/server.go:298 adding route {"url": "/ext/health", "endpoint": "/liveness"},
[09-08|06:10:57.419] INFO node/node.go:630 adding the default VM aliases,
[09-08|06:10:57.657] INFO node/node.go:748 initializing VMs,
[09-08|06:10:57.657] INFO server/server.go:298 adding route {"url": "/ext/vm/rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT", "endpoint": ""},
[09-08|06:10:57.657] INFO server/server.go:298 adding route {"url": "/ext/vm/jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq", "endpoint": ""},
[09-08|06:10:57.657] INFO server/server.go:298 adding route {"url": "/ext/vm/mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6", "endpoint": "/rpc"},
[09-08|06:10:57.657] INFO node/node.go:910 skipping admin API initialization because it has been disabled,
[09-08|06:10:57.657] INFO node/node.go:962 initializing info API,
[09-08|06:10:57.657] INFO server/server.go:298 adding route {"url": "/ext/info", "endpoint": ""},
[09-08|06:10:57.657] INFO node/node.go:1112 skipping ipc API initialization because it has been disabled,
[09-08|06:10:57.657] INFO node/node.go:1125 initializing chain aliases,
[09-08|06:10:58.122] INFO node/node.go:1143 initializing API aliases,
[09-08|06:10:58.282] INFO node/node.go:935 skipping profiler initialization because it has been disabled,
[09-08|06:10:58.282] INFO node/node.go:569 initializing chains,
[09-08|06:10:58.282] INFO chains/manager.go:265 creating chain {"chainID": "11111111111111111111111111111111LpoYY", "vmID": "rWhpuQPF1kb72esV2momhMuTYGkEb1oL29pt2EBXWmSy4kxnT"},
[09-08|06:10:59.751] INFO <P Chain> platformvm/vm.go:228 initializing last accepted {"blkID": "mTQzvaBDrQM4JCg1brrmyQ7Rtoc3zAzshojPEcvE6g4eXD1Fg"},
[09-08|06:10:59.754] INFO <P Chain> snowman/transitive.go:80 initializing consensus engine,
[09-08|06:10:59.755] INFO server/server.go:272 adding route {"url": "/ext/bc/11111111111111111111111111111111LpoYY", "endpoint": ""},
[09-08|06:10:59.755] INFO <P Chain> bootstrap/bootstrapper.go:115 starting bootstrapper,
[09-08|06:10:59.755] INFO server/server.go:173 HTTP API server listening {"host": "0.0.0.0", "port": 9650},
[09-08|06:11:05.696] INFO <P Chain> common/bootstrapper.go:248 bootstrapping started syncing {"numVerticesInFrontier": 1},
[09-08|06:11:05.696] INFO <P Chain> bootstrap/bootstrapper.go:528 executing blocks {"numPendingJobs": 0},
[09-08|06:11:05.696] INFO <P Chain> queue/jobs.go:208 executed operations {"numExecuted": 0},
[09-08|06:11:05.696] INFO chains/manager.go:265 creating chain {"chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "vmID": "mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6"},
INFO [09-08|06:11:05.697] <C Chain> github.com/ava-labs/coreth/plugin/evm/vm.go:352: Initializing Coreth VM Version=v0.9.0 Config="{SnowmanAPIEnabled:false CorethAdminAPIEnabled:false CorethAdminAPIDir: EnabledEthAPIs:[internal-public-eth internal-public-blockchain internal-public-transaction-pool internal-public-tx-pool internal-public-debug internal-private-debug debug-tracer web3 public-eth public-eth-filter public-debug private-debug net] ContinuousProfilerDir: ContinuousProfilerFrequency:15m0s ContinuousProfilerMaxFiles:5 RPCGasCap:2500000000 RPCTxFeeCap:100 Preimages:false SnapshotAsync:true SnapshotVerify:false Pruning:false AcceptorQueueLimit:64 CommitInterval:4096 AllowMissingTries:false PopulateMissingTries:<nil> PopulateMissingTriesParallelism:1024 MetricsExpensiveEnabled:true LocalTxsEnabled:false APIMaxDuration:0s WSCPURefillRate:0s WSCPUMaxStored:0s MaxBlocksPerRequest:0 AllowUnfinalizedQueries:false AllowUnprotectedTxs:false KeystoreDirectory: KeystoreExternalSigner: KeystoreInsecureUnlockAllowed:false RemoteTxGossipOnlyEnabled:false TxRegossipFrequency:1m0s TxRegossipMaxSize:15 LogLevel:info LogJSONFormat:false OfflinePruning:false OfflinePruningBloomFilterSize:512 OfflinePruningDataDirectory: MaxOutboundActiveRequests:16 StateSyncEnabled:false StateSyncSkipResume:false StateSyncServerTrieCache:64 StateSyncIDs: StateSyncCommitInterval:16384 StateSyncMinBlocks:300000}",
INFO [09-08|06:11:05.700] <C Chain> github.com/ava-labs/coreth/trie/database.go:722: Persisted trie from memory database nodes=1 size=140.00B time="6.202µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B,
INFO [09-08|06:11:05.700] <C Chain> github.com/ava-labs/coreth/plugin/evm/vm.go:455: lastAccepted = 0x5fb201239367aca962664c1de147c5c53b31fc85894ac256dcfe22a8387c7719 ,

**INFO [09-08|06:11:05.701] <C Chain> github.com/ava-labs/coreth/eth/backend.go:147: Allocated trie memory caches clean=448.00MiB dirty=256.00MiB,
INFO [09-08|06:11:05.702] <C Chain> github.com/ava-labs/coreth/trie/database.go:722: Persisted trie from memory database nodes=1 size=140.00B time="3.958µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B,
[09-08|06:11:05.702] FATAL chains/manager.go:288 error creating required chain {"chainID": "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5", "error": "error while creating new snowman vm mismatching ApricotPhasePre6 fork block timestamp in database (have <nil>, want 1662341400, rewindto 1662341399)"},
[09-08|06:11:05.702] INFO chains/manager.go:265 creating chain {"chainID": "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", "vmID": "jvYyfQTxGMJLuGWa55kdP2p2zSUYsQ5Raupu4TW34ZAUBAbtq"},
[09-08|06:11:05.703] INFO node/node.go:1334 shutting down node {"exitCode": 1},**

[09-08|06:11:05.703] INFO ipcs/chainipc.go:111 shutting down chain IPCs,
[09-08|06:11:05.703] INFO chains/manager.go:992 shutting down chain manager,
[09-08|06:11:05.703] INFO router/chain_router.go:274 shutting down chain router,
[09-08|06:11:05.712] INFO <X Chain> avm/vm.go:458 fee asset is established {"alias": "AVAX", "assetID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z"},
[09-08|06:11:05.712] INFO <X Chain> avm/vm.go:240 address transaction indexing is disabled,
[09-08|06:11:05.734] INFO <X Chain> avalanche/transitive.go:74 initializing consensus engine,
[09-08|06:11:05.735] INFO server/server.go:272 adding route {"url": "/ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", "endpoint": "/events"},
[09-08|06:11:05.735] INFO <X Chain> bootstrap/bootstrapper.go:313 starting bootstrap,
[09-08|06:11:05.735] INFO <P Chain> bootstrap/bootstrapper.go:571 waiting for the remaining chains in this subnet to finish syncing,
[09-08|06:11:05.735] INFO server/server.go:272 adding route {"url": "/ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", "endpoint": ""},
[09-08|06:11:05.735] INFO <P Chain> bootstrap/bootstrapper.go:282 shutting down bootstrapper,
[09-08|06:11:05.735] INFO network/network.go:1064 shutting down the p2p networking,
[09-08|06:11:05.735] INFO server/server.go:272 adding route {"url": "/ext/bc/2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM", "endpoint": "/wallet"},
[09-08|06:11:05.748] INFO node/node.go:1387 cleaning up plugin subprocesses,
[09-08|06:11:05.753] INFO node/node.go:1399 finished node shutdown,
[09-08|06:11:05.753] INFO nat/nat.go:180 Unmapped all ports,
2022/09/08 06:11:05 command /app/avalanchego finished, error: <nil>,
panic: os: process already finished,
,
goroutine 65 [running]:,
main.startCommand.func1(),
	/go/src/github.com/ava-labs/avalanche-rosetta/cmd/runner/main.go:93 +0x72,
created by main.startCommand,
	/go/src/github.com/ava-labs/avalanche-rosetta/cmd/runner/main.go:89 +0x2ea,

**Comment by rajranjan0608** [comment]
This issue has been resolved with the latest update. Now you can upgrade your node directly to 1.8.5 from 1.7.x
